# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('1', '_1'), ('2', '_2'), ('3', '_3'), ('4', '_4'), ('5', '_5'), ('6', '_6'), ('7', '_7'), ('8', '_8'), ('9', '_9'), ('10', '_10'), ('11', '_11'), ('12', '_12'), ('13', '_13'), ('14', '_14'), ('15', '_15'), ('16', '_16'), ('17', '_17'), ('18', '_18'), ('19', '_19'), ('20', '_20'), ('21', '_21'), ('22', '_22'), ('23', '_23'), ('24', '_24')], max_length=2),
        ),
        migrations.AlterField(
            model_name='day',
            name='image_large',
            field=image_cropping.fields.ImageRatioField('image', '1200x1200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image large'),
        ),
    ]
