# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-19 17:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('calendar', '0003_auto_20161117_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='day',
            name='original_image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image'),
        ),
    ]
