# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-19 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_auto_20161119_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='image',
        ),
    ]
