# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0005_remove_day_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='image_large',
        ),
        migrations.RemoveField(
            model_name='day',
            name='image_small',
        ),
    ]
